- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: eur
  fixed: 2
  fee_max: 0
  min: 1
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelEthereum
- id: 900
  key: mexican
  currency: mxn
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelMexican
- id: 700
  key: dollar
  currency: usd
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelDollar
  